version: "3.8"

services:
  traefik:
    image: traefik:latest
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      # For HTTPS in production
      # - target: 443
      #   published: 443
      #   protocol: tcp
      #   mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ./data/acme.json:/acme.json
    networks:
      - public-net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        # This label just lets Traefik discover itself; the dashboard route will be defined in dynamic.yml
        - "traefik.docker.network=public-net"

networks:
  public-net:
    external: true
